### ISSUE TITLE
Issues in content.opf

### ISSUE THREAD

**Issue by robinwhittleton** [maack11/e-nesbit_the-story-of-the-treasure-seekers#2]
- file as for fulltitle should be the full title, not just the first half
- the `dc:subject`s look a little odd, typically they’d have a normal space before and after the `--` . It looks like you’ve run typogrify specifically against this as the `dc:date` and `dcterms:modified` entries also seemed to have gained en-dashes and hairspaces. This was done in https://github.com/maack11/e-nesbit_the-story-of-the-treasure-seekers/commit/2f9155d6
- Typically the collection metadata goes above the short description and below the `se:subject`(s)

**Comment by maack11** [comment]
Alright. That means the example in the SEMOS is wrong, because that does not include the full title in the file-as full title! :)

**Comment by robinwhittleton** [comment]
Right, yep, that does look wrong. PRed a fix for that at https://github.com/standardebooks/manual/pull/129.
