### ISSUE TITLE
Remove xml:lang from French poems

### ISSUE THREAD

**Issue by robinwhittleton** [maack11/e-nesbit_the-story-of-the-treasure-seekers#6]
https://github.com/maack11/e-nesbit_the-story-of-the-treasure-seekers/blob/40b059723a5067778e11b0707acd758504c61cd9/src/epub/text/chapter-8.xhtml#L200

As the divs have English headers you should put the `xml:lang="fr"` on the verse `<p>`s instead. There’s a few more changes to make too:

- For container `xml:lang` references we need an additional CSS namespace and rule to italicise them. See https://standardebooks.org/manual/1.7.0/single-page#5.3.1.3
- There’s the `<span xml:lang="en-GB">` that we don’t want in italics. You could write a special rule to remove it there. Maybe something like:

```css
#chapter-8 span[xml|lang]{
  font-style: normal;
}
```

**Comment by maack11** [comment]
I'd appreciate it if you could check if I fixed this issue correctly when I push the commit :)

**Comment by robinwhittleton** [comment]
Almost 🙂 What I’d do is:

1. Move the `xml:lang="fr"` up from the `<span>`s to the parent `<p>`. You can also put the mixed line back to how it was: `<span>Était <span xml:lang="en-GB">over the hills and far away.</span></span>`.
2. Remove the specific languages from the new CSS (so `body [xml|lang]` and `#chapter-8 span[xml|lang]`).

**Comment by maack11** [comment]
I see, thank you! When I tried the css like that, it didn't work, but that was because I'd put all the xml:lang on <span> level. That's why I thought I needed to specify the language. But that's not needed when we specify the _body_ to be italic, and the span level xml:lang to be non-italic. Still learning how to read css :)
