### ISSUE TITLE
up stairs -> upstairs

### ISSUE THREAD

**Issue by robinwhittleton** [maack11/e-nesbit_the-story-of-the-treasure-seekers#7]
https://github.com/maack11/e-nesbit_the-story-of-the-treasure-seekers/blob/40b059723a5067778e11b0707acd758504c61cd9/src/epub/text/chapter-9.xhtml#L73

`modernize-spelling` changes “up stairs” to “upstairs”. I think this is correct.

**Comment by maack11** [comment]
I read it as the stairs have soft carpets, not the upstairs. So they go up the stairs, which have soft carpets. So I am hesitant to change this.

**Comment by robinwhittleton** [comment]
OK 🙂 Happy to go with your judgment here.
